CREATE TABLE [dbo].[DIM_CUSTOMER]
(
	[CUS_ID] VARCHAR(50) NOT NULL PRIMARY KEY, 
    [CUS_NAME] NVARCHAR(50) NULL, 
    [CUS_REGION] NVARCHAR(50) NULL, 
    [CUS_REGION_CHINESE] NVARCHAR(50) NULL, 
    [CUS_RANK] NVARCHAR(50) NULL, 
    [CHANNEL] NVARCHAR(50) NULL, 
	[PROVINCE] NVARCHAR(50) NULL,
    [IS_DOCKED] BIT NULL 
)
