CREATE TABLE [dbo].[DIM_CUBE_CALENDAR]
(
	[DDATE] VARCHAR(8) NOT NULL PRIMARY KEY, 
    [YEAR] VARCHAR(4) NOT NULL, 
    [MONTH] VARCHAR(4) NULL, 
    [WEEKCALENDAR_YEAR] VARCHAR(4) NULL, 
    [WEEKCALENDAR_WEEK] VARCHAR(2) NULL, 
    [WEEKDAY] VARCHAR(20) NULL, 
    [ISWEEKEND] BIT NULL, 
    [ISMONTHEND] BIT NULL
)
