CREATE TABLE [dbo].[FACT_TRANFER_RECORD]
(
	[ID] BIGINT NOT NULL PRIMARY KEY IDENTITY, 
	[DDATE] DATE NOT NULL,
    [VOUCHER_ID] VARCHAR(50) NULL, 
    [VOUCHER_AUTOID] VARCHAR(50) NULL, 
    [VOUCHER_TYPE] VARCHAR(50) NULL, 
    [CUS_ID] VARCHAR(50) NULL, 
    [WHSE_ID] VARCHAR(2) NULL, 
    CONSTRAINT [FK_FACT_TRANFER_RECORD_TOCUSTOMER] FOREIGN KEY ([CUS_ID]) REFERENCES [DIM_CUSTOMER]([CUS_ID]), 
    CONSTRAINT [FK_FACT_TRANFER_RECORD_TOWHSE] FOREIGN KEY ([WHSE_ID]) REFERENCES [DIM_WAREHOUSE]([WHSE_ID]) 
)
